version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp_final
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network

  symfony-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-symfony-app
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
